class CfgPatches
{
	class A3_Data_F_Rus_Loadorder
	{
		addonRootClass="A3_Data_F_Rus";
		requiredAddons[]=
		{
			"A3_Air_F_Rus",
			"A3_Air_F_Rus_Heli_Attack_02",
			"A3_Air_F_Rus_Heli_Light_02",
			"A3_Air_F_Rus_Heli_Transport_04",
			"A3_Air_F_Rus_Plane_CAS_02",
			"A3_Air_F_Rus_Plane_Fighter_02",
			"A3_Air_F_Rus_UAV_01",
			"A3_Air_F_Rus_UAV_02",
			"A3_Air_F_Rus_UAV_06",
			"A3_Armor_F_Rus",
			"A3_Armor_F_Rus_APC_Tracked_02",
			"A3_Armor_F_Rus_APC_Wheeled_02",
			"A3_Armor_F_Rus_MBT_02",
			"A3_Armor_F_Rus_MBT_04",
			"A3_Boat_F_Rus",
			"A3_Boat_F_Rus_Boat_Armed_01",
			"A3_Boat_F_Rus_Boat_Transport_01",
			"A3_Boat_F_Rus_Boat_Transport_02",
			"A3_Boat_F_Rus_SDV_01",
			"A3_Characters_F_Rus",
			"A3_Characters_F_Rus_Headgear",
			"A3_Characters_F_Rus_Uniforms",
			"A3_Characters_F_Rus_Vests",
			"A3_Data_F_Rus",
			"A3_Dubbing_Radio_F_Rus",
			"A3_EditorPreviews_F_Rus",
			"A3_Language_F_Rus",
			"A3_Music_F_Rus",
			"A3_Soft_F_Rus",
			"A3_Soft_F_Rus_LSV_02",
			"A3_Soft_F_Rus_MRAP_02",
			"A3_Soft_F_Rus_Quadbike_01",
			"A3_Soft_F_Rus_Truck_02",
			"A3_Soft_F_Rus_Truck_03",
			"A3_Soft_F_Rus_UGV_01",
			"A3_Sounds_F_Rus",
			"A3_Static_F_Rus",
			"A3_Static_F_Rus_AA_01",
			"A3_Static_F_Rus_AAA_System_01",
			"A3_Static_F_Rus_AT_01",
			"A3_Static_F_Rus_Designator_01",
			"A3_Static_F_Rus_GMG_01",
			"A3_Static_F_Rus_HMG_01",
			"A3_Static_F_Rus_Mortar_01",
			"A3_Static_F_Rus_SAM_System_01",
			"A3_Static_F_Rus_SAM_System_02",
			"A3_Structures_F_Rus",
			"A3_Structures_F_Rus_Humanitarian",
			"A3_Structures_F_Rus_Humanitarian_Camps",
			"A3_Structures_F_Rus_Military",
			"A3_Structures_F_Rus_Military_Flags",
			"A3_Structures_F_Rus_Signs",
			"A3_Structures_F_Rus_Signs_Warnings",
			"A3_Supplies_F_Rus",
			"A3_Supplies_F_Rus_Ammoboxes",
			"A3_Supplies_F_Rus_Bags",
			"A3_Supplies_F_Rus_CargoNets",
			"A3_UI_F_Rus",
			"A3_Weapons_F_Rus",
			"A3_Weapons_F_Rus_Acc",
			"A3_Weapons_F_Rus_GrenadeLaunchers_RG6",
			"A3_Weapons_F_Rus_Launchers_Titan",
			"A3_Weapons_F_Rus_LongRangeRifles_DMR_01",
			"A3_Weapons_F_Rus_LongRangeRifles_DMR_04",
			"A3_Weapons_F_Rus_LongRangeRifles_DMR_05",
			"A3_Weapons_F_Rus_Machineguns_MMG_03",
			"A3_Weapons_F_Rus_Rifles_AK105",
			"A3_Weapons_F_Rus_Rifles_AK107",
			"A3_Weapons_F_Rus_Rifles_AK12",
			"A3_Weapons_F_Rus_Rifles_RPK",
			"A3_Weapons_F_Rus_Shotguns_SK12",
			"A3_Weapons_F_Rus_SMGs_SMG_06"
		};
		requiredVersion=0.1;
		units[]={};
		weapons[]={};
	};
};
class cfgMods
{
	author="Night515";
	timepacked="1527346175";
};
