class CfgPatches
{
	class A3_Weapons_F_Aegis_Shotguns_KSG
	{
		addonRootClass="A3_Weapons_F_Aegis";
		requiredAddons[]=
		{
			"A3_Weapons_F_Aegis"
		};
		requiredVersion=0.1;
		units[]=
		{
			"Weapon_sgun_KSG_black_F",
			"Weapon_sgun_KSG_F"
		};
		weapons[]=
		{
			"sgun_KSG_ACO_F",
			"sgun_KSG_black_ACO_F",
			"sgun_KSG_black_F",
			"sgun_KSG_F"
		};
	};
};
class Mode_SemiAuto;
class Mode_Burst;
class Mode_FullAuto;
class MuzzleSlot;
class CowsSlot;
class PointerSlot;
class CfgWeapons
{
	class Rifle_Base_F;
	class Rifle_Short_Base_F: Rifle_Base_F
	{
		class WeaponSlotsInfo;
	};
	class UGL_F;
	class sgun_KSG_F: Rifle_Short_Base_F
	{
		author="$STR_A3_Night515";
		_generalMacro="sgun_KSG_F";
		baseWeapon="sgun_KSG_F";
		scope=2;
		displayName="$STR_A3_CfgWeapons_sgun_KSG0";
		model="\A3\Weapons_F_Aegis\Shotguns\KSG\KSG_F.p3d";
		magazines[]=
		{
			"8Rnd_12Gauge_Pellets",
			"8Rnd_12Gauge_Slug"
		};
		maxZeroing=100;
		reloadAction="GestureReloadM4SSAS";
		recoil="recoil_ksg";
		cursor="sgun";
		discreteDistanceInitIndex=0;
		aiDispersionCoefY=8;
		aiDispersionCoefX=6;
		handAnim[]=
		{
			"OFP2_ManSkeleton",
			"\A3\Weapons_F\Machineguns\M200\Data\Anim\M200.rtm"
		};
		class WeaponSlotsInfo: WeaponSlotsInfo
		{
			mass=120;
			class MuzzleSlot
			{
			};
			class CowsSlot: CowsSlot
			{
				iconPosition[]={0.34,0.31999999};
				iconScale=0.2;
			};
			class PointerSlot: PointerSlot
			{
				linkProxy="\A3\Data_F\proxies\weapon_slots\SIDE";
				compatibleItems[]=
				{
					"acc_flashlight_pistol"
				};
				iconPosition[]={0.23999999,0.34999999};
				iconScale=0.2;
			};
			class UnderbarrelSlot
			{
			};
		};
		inertia=0.5;
		aimTransitionSpeed=1.2;
		dexterity=1.5;
		initSpeed=350;
		muzzles[]=
		{
			"this",
			"Secondary"
		};
		picture="\A3\Weapons_F_Aegis\Shotguns\KSG\Data\UI\gear_KSG_X_CA.paa";
		UiPicture="\A3\Weapons_F\Data\UI\icon_regular_CA.paa";
		descriptionShort="$STR_A3_CfgWeapons_sgun_KSG1";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Weapons_F_Aegis\Shotguns\KSG\Data\KSG_CO.paa"
		};
		class Library
		{
			libTextDesc="$STR_A3_CfgWeapons_sgun_KSG_Library0";
		};
		bullet1[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_01",
			0.79432821,
			1,
			15
		};
		bullet2[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_02",
			0.79432821,
			1,
			15
		};
		bullet3[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_03",
			0.79432821,
			1,
			15
		};
		bullet4[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_04",
			0.79432821,
			1,
			15
		};
		bullet5[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_01",
			0.79432821,
			1,
			15
		};
		bullet6[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_02",
			0.79432821,
			1,
			15
		};
		bullet7[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_03",
			0.79432821,
			1,
			15
		};
		bullet8[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_04",
			0.79432821,
			1,
			15
		};
		bullet9[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_01",
			0.79432821,
			1,
			15
		};
		bullet10[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_02",
			0.79432821,
			1,
			15
		};
		bullet11[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_03",
			0.79432821,
			1,
			15
		};
		bullet12[]=
		{
			"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_04",
			0.79432821,
			1,
			15
		};
		soundBullet[]=
		{
			"bullet1",
			0.082999997,
			"bullet2",
			0.082999997,
			"bullet3",
			0.082999997,
			"bullet4",
			0.082999997,
			"bullet5",
			0.082999997,
			"bullet6",
			0.082999997,
			"bullet7",
			0.082999997,
			"bullet8",
			0.082999997,
			"bullet9",
			0.082999997,
			"bullet10",
			0.082999997,
			"bullet11",
			0.082999997,
			"bullet12",
			0.082999997
		};
		distanceZoomMin=100;
		distanceZoomMax=100;
		drySound[]=
		{
			"A3\Sounds_F_Aegis\arsenal\weapons\Shotguns\KSG\dry_KSG",
			0.69999999,
			1,
			10
		};
		reloadMagazineSound[]=
		{
			"A3\Sounds_F_Aegis\arsenal\weapons\Shotguns\KSG\reload_KSG",
			1,
			1,
			10
		};
		changeFiremodeSound[]=
		{
			"A3\Sounds_F_Aegis\arsenal\weapons\Shotguns\KSG\firemode_KSG",
			0.5,
			1,
			5
		};
		modes[]=
		{
			"Single"
		};
		class Single: Mode_SemiAuto
		{
			sounds[]=
			{
				"StandardSound"
			};
			class BaseSoundModeType;
			class StandardSound: BaseSoundModeType
			{
				soundSetShot[]=
				{
					"KSG_Shot_SoundSet",
					"KSG_Tail_SoundSet",
					"KSG_interiorTail_SoundSet"
				};
			};
			dispersion=0.00131;
			reloadTime=0.75;
			minRange=1;
			minRangeProbab=0.5;
			midRange=50;
			midRangeProbab=0.69999999;
			maxRange=100;
			maxRangeProbab=0.2;
		};
		class Secondary: Rifle_Short_Base_F
		{
			displayName="$STR_A3_CfgWeapons_sgun_KSG0";
			model="\A3\Weapons_F_Aegis\Shotguns\KSG\KSG_F.p3d";
			magazines[]=
			{
				"8Rnd_12Gauge_Pellets",
				"8Rnd_12Gauge_Slug"
			};
			maxZeroing=300;
			reloadAction="GestureReloadM4SSAS";
			recoil="recoil_ksg";
			cursor="sgun";
			discreteDistanceInitIndex=0;
			inertia=0.5;
			aimTransitionSpeed=1.2;
			dexterity=1.5;
			initSpeed=350;
			bullet1[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_01",
				0.79432821,
				1,
				15
			};
			bullet2[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_02",
				0.79432821,
				1,
				15
			};
			bullet3[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_03",
				0.79432821,
				1,
				15
			};
			bullet4[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\metal_shotgun_04",
				0.79432821,
				1,
				15
			};
			bullet5[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_01",
				0.79432821,
				1,
				15
			};
			bullet6[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_02",
				0.79432821,
				1,
				15
			};
			bullet7[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_03",
				0.79432821,
				1,
				15
			};
			bullet8[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\dirt_shotgun_04",
				0.79432821,
				1,
				15
			};
			bullet9[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_01",
				0.79432821,
				1,
				15
			};
			bullet10[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_02",
				0.79432821,
				1,
				15
			};
			bullet11[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_03",
				0.79432821,
				1,
				15
			};
			bullet12[]=
			{
				"A3\Sounds_F_Aegis\weapons\shells\Shotgun\grass_shotgun_04",
				0.79432821,
				1,
				15
			};
			soundBullet[]=
			{
				"bullet1",
				0.082999997,
				"bullet2",
				0.082999997,
				"bullet3",
				0.082999997,
				"bullet4",
				0.082999997,
				"bullet5",
				0.082999997,
				"bullet6",
				0.082999997,
				"bullet7",
				0.082999997,
				"bullet8",
				0.082999997,
				"bullet9",
				0.082999997,
				"bullet10",
				0.082999997,
				"bullet11",
				0.082999997,
				"bullet12",
				0.082999997
			};
			distanceZoomMin=100;
			distanceZoomMax=100;
			drySound[]=
			{
				"A3\Sounds_F_Aegis\arsenal\weapons\Shotguns\KSG\dry_KSG",
				0.69999999,
				1,
				10
			};
			reloadMagazineSound[]=
			{
				"A3\Sounds_F_Aegis\arsenal\weapons\Shotguns\KSG\reload_KSG",
				1,
				1,
				10
			};
			changeFiremodeSound[]=
			{
				"A3\Sounds_F_Aegis\arsenal\weapons\Shotguns\KSG\firemode_KSG",
				0.5,
				1,
				5
			};
			modes[]=
			{
				"Single"
			};
			class Single: Mode_SemiAuto
			{
				sounds[]=
				{
					"StandardSound"
				};
				class BaseSoundModeType;
				class StandardSound: BaseSoundModeType
				{
					soundSetShot[]=
					{
						"KSG_Shot_SoundSet",
						"KSG_Tail_SoundSet",
						"KSG_interiorTail_SoundSet"
					};
				};
				dispersion=0.00131;
				reloadTime=0.75;
				minRange=1;
				minRangeProbab=0.5;
				midRange=50;
				midRangeProbab=0.69999999;
				maxRange=100;
				maxRangeProbab=0.2;
			};
		};
		DLC="Aegis";
	};
	class sgun_KSG_black_F: sgun_KSG_F
	{
		author="$STR_A3_Night515";
		_generalMacro="sgun_KSG_black_F";
		baseWeapon="sgun_KSG_black_F";
		displayName="Bulldog 12 Gauge (Black)";
		hiddenSelectionsTextures[]=
		{
			"\A3\Weapons_F_Aegis\Shotguns\KSG\Data\KSG_black_CO.paa"
		};
		picture="\A3\Weapons_F_Aegis\Shotguns\KSG\Data\UI\gear_KSG_black_X_CA.paa";
		DLC="Aegis";
	};
	class sgun_KSG_ACO_F: sgun_KSG_F
	{
		author="$STR_A3_Night515";
		_generalMacro="sgun_KSG_ACO_F";
		baseWeapon="sgun_KSG_F";
		scope=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_ACO_smg";
			};
		};
	};
	class sgun_KSG_black_ACO_F: sgun_KSG_black_F
	{
		author="$STR_A3_Night515";
		_generalMacro="sgun_KSG_black_ACO_F";
		baseWeapon="sgun_KSG_black_F";
		scope=1;
		class LinkedItems
		{
			class LinkedItemsOptic
			{
				slot="CowsSlot";
				item="optic_ACO_smg";
			};
		};
	};
};
class CfgVehicles
{
	class Weapon_Base_F;
	class Weapon_sgun_KSG_F: Weapon_Base_F
	{
		scope=2;
		scopeCurator=2;
		displayName="$STR_A3_CfgWeapons_sgun_KSG0";
		author="$STR_A3_Night515";
		editorCategory="EdCat_Weapons";
		editorSubcategory="EdSubcat_Shotguns";
		vehicleClass="WeaponsPrimary";
		class TransportWeapons
		{
			class _xx_sgun_KSG_F
			{
				weapon="sgun_KSG_F";
				count=1;
			};
		};
		class TransportMagazines
		{
			class _xx_8Rnd_12Gauge_Pellets
			{
				magazine="8Rnd_12Gauge_Pellets";
				count=1;
			};
		};
	};
	class Weapon_sgun_KSG_black_F: Weapon_Base_F
	{
		scope=2;
		scopeCurator=2;
		displayName="Bulldog 12 Gauge (Black)";
		author="$STR_A3_Night515";
		editorCategory="EdCat_Weapons";
		editorSubcategory="EdSubcat_Shotguns";
		vehicleClass="WeaponsPrimary";
		class TransportWeapons
		{
			class _xx_sgun_KSG_black_F
			{
				weapon="sgun_KSG_black_F";
				count=1;
			};
		};
		class TransportMagazines
		{
			class _xx_8Rnd_12Gauge_Pellets
			{
				magazine="8Rnd_12Gauge_Pellets";
				count=1;
			};
		};
	};
};
class cfgMods
{
	author="Night515";
	timepacked="1528895047";
};
