class CfgPatches
{
	class A3_Soft_F_Aegis_Truck_02
	{
		addonRootClass="A3_Soft_F_Aegis";
		requiredAddons[]=
		{
			"A3_Soft_F_Beta_Truck_02",
			"A3_Soft_F_Gamma_Truck_02"
		};
		requiredVersion=0.1;
		units[]=
		{
			"O_A_Truck_02_Ammo_F",
			"O_A_Truck_02_box_F",
			"O_A_Truck_02_covered_F",
			"O_A_Truck_02_fuel_F",
			"O_A_Truck_02_medical_F",
			"O_A_Truck_02_MRL_F",
			"O_A_Truck_02_transport_F",
			"O_T_Truck_02_Ammo_ghex_F",
			"O_T_Truck_02_box_ghex_F",
			"O_T_Truck_02_covered_ghex_F",
			"O_T_Truck_02_fuel_ghex_F",
			"O_T_Truck_02_medical_ghex_F",
			"O_T_Truck_02_MRL_ghex_F",
			"O_T_Truck_02_transport_ghex_F",
			"O_Truck_02_MRL_F"
		};
		weapons[]={};
	};
};
class CfgVehicles
{
	class Truck_F;
	class Truck_02_base_F: Truck_F
	{
		class TextureSources
		{
			class GreenHex
			{
				displayName="$STR_A3_TEXTURESOURCES_GREENHEX0";
				author="$STR_A3_Night515";
				textures[]=
				{
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kuz_ghex_CO.paa",
					"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
				};
				factions[]=
				{
					"OPF_T_F"
				};
			};
		};
	};
	class Truck_02_transport_base_F: Truck_02_base_F
	{
		class TextureSources
		{
			class GreenHex
			{
				displayName="$STR_A3_TEXTURESOURCES_GREENHEX0";
				author="$STR_A3_Night515";
				textures[]=
				{
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kuz_ghex_CO.paa",
					"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
				};
				factions[]=
				{
					"OPF_T_F"
				};
			};
		};
	};
	class Truck_02_box_base_F: Truck_02_base_F
	{
		class TextureSources
		{
			class GreenHex
			{
				displayName="$STR_A3_TEXTURESOURCES_GREENHEX0";
				author="$STR_A3_Night515";
				textures[]=
				{
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_repair_ghex_CO.paa",
					"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
				};
				factions[]=
				{
					"OPF_T_F"
				};
			};
		};
	};
	class Truck_02_medical_base_F: Truck_02_box_base_F
	{
		class TextureSources
		{
			class GreenHex
			{
				displayName="$STR_A3_TEXTURESOURCES_GREENHEX0";
				author="$STR_A3_Night515";
				textures[]=
				{
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kuz_ghex_CO.paa",
					"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
				};
				factions[]=
				{
					"OPF_T_F"
				};
			};
		};
	};
	class Truck_02_Ammo_base_F: Truck_02_base_F
	{
		class TextureSources
		{
			class GreenHex
			{
				displayName="$STR_A3_TEXTURESOURCES_GREENHEX0";
				author="$STR_A3_Night515";
				textures[]=
				{
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_repair_ghex_CO.paa",
					"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
				};
				factions[]=
				{
					"OPF_T_F"
				};
			};
		};
	};
	class Truck_02_fuel_base_F: Truck_02_base_F
	{
		class TextureSources
		{
			class GreenHex
			{
				displayName="$STR_A3_TEXTURESOURCES_GREENHEX0";
				author="$STR_A3_Night515";
				textures[]=
				{
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
					"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_fuel_ghex_CO.paa",
					"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
				};
				factions[]=
				{
					"OPF_T_F"
				};
			};
		};
	};
	class Truck_02_MRL_base_F: Truck_02_base_F
	{
	};
	class O_Truck_02_transport_F;
	class O_T_Truck_02_transport_ghex_F: O_Truck_02_transport_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_T_Truck_02_transport_ghex_F.jpg";
		_generalMacro="O_T_Truck_02_transport_ghex_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_T_F";
		crew="O_T_Soldier_F";
		typicalCargo[]=
		{
			"O_T_Soldier_F"
		};
		textureList[]=
		{
			"GreenHex",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kuz_ghex_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_A_Truck_02_transport_F: O_Truck_02_transport_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_A_Truck_02_transport_F.jpg";
		_generalMacro="O_A_Truck_02_transport_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_A_F";
		crew="O_A_soldier_F";
		typicalCargo[]=
		{
			"O_A_soldier_F"
		};
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kuz_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_Truck_02_covered_F;
	class O_T_Truck_02_covered_ghex_F: O_Truck_02_covered_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_T_Truck_02_covered_ghex_F.jpg";
		_generalMacro="O_T_Truck_02_covered_ghex_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_T_F";
		crew="O_T_Soldier_F";
		typicalCargo[]=
		{
			"O_T_Soldier_F"
		};
		textureList[]=
		{
			"GreenHex",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kuz_ghex_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_A_Truck_02_covered_F: O_Truck_02_covered_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_A_Truck_02_covered_F.jpg";
		_generalMacro="O_A_Truck_02_covered_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_A_F";
		crew="O_A_soldier_F";
		typicalCargo[]=
		{
			"O_A_soldier_F"
		};
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kuz_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_Truck_02_box_F;
	class O_T_Truck_02_box_ghex_F: O_Truck_02_box_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_T_Truck_02_box_ghex_F.jpg";
		_generalMacro="O_T_Truck_02_box_ghex_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_T_F";
		crew="O_T_Soldier_F";
		typicalCargo[]=
		{
			"O_T_Soldier_F"
		};
		textureList[]=
		{
			"GreenHex",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_repair_ghex_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_A_Truck_02_box_F: O_Truck_02_box_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_A_Truck_02_box_F.jpg";
		_generalMacro="O_A_Truck_02_box_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_A_F";
		crew="O_A_soldier_F";
		typicalCargo[]=
		{
			"O_A_soldier_F"
		};
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_repair_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_Truck_02_medical_F;
	class O_T_Truck_02_medical_ghex_F: O_Truck_02_medical_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_T_Truck_02_medical_ghex_F.jpg";
		_generalMacro="O_T_Truck_02_medical_ghex_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_T_F";
		crew="O_T_Soldier_F";
		typicalCargo[]=
		{
			"O_T_Soldier_F"
		};
		textureList[]=
		{
			"GreenHex",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kuz_ghex_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_A_Truck_02_medical_F: O_Truck_02_medical_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_A_Truck_02_medical_F.jpg";
		_generalMacro="O_A_Truck_02_medical_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_A_F";
		crew="O_A_soldier_F";
		typicalCargo[]=
		{
			"O_A_soldier_F"
		};
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kuz_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_Truck_02_Ammo_F;
	class O_T_Truck_02_Ammo_ghex_F: O_Truck_02_Ammo_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_T_Truck_02_Ammo_ghex_F.jpg";
		_generalMacro="O_T_Truck_02_Ammo_ghex_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_T_F";
		crew="O_T_Soldier_F";
		typicalCargo[]=
		{
			"O_T_Soldier_F"
		};
		textureList[]=
		{
			"GreenHex",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_repair_ghex_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_A_Truck_02_Ammo_F: O_Truck_02_Ammo_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_A_Truck_02_Ammo_F.jpg";
		_generalMacro="O_A_Truck_02_Ammo_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_A_F";
		crew="O_A_soldier_F";
		typicalCargo[]=
		{
			"O_A_soldier_F"
		};
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_repair_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_Truck_02_fuel_F;
	class O_T_Truck_02_fuel_ghex_F: O_Truck_02_fuel_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_T_Truck_02_fuel_ghex_F.jpg";
		_generalMacro="O_T_Truck_02_fuel_ghex_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_T_F";
		crew="O_T_Soldier_F";
		typicalCargo[]=
		{
			"O_T_Soldier_F"
		};
		textureList[]=
		{
			"GreenHex",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_fuel_ghex_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_A_Truck_02_fuel_F: O_Truck_02_fuel_F
	{
		author="$STR_A3_Night515";
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_A_Truck_02_fuel_F.jpg";
		_generalMacro="O_A_Truck_02_fuel_F";
		scope=2;
		scopeCurator=2;
		DLC="Aegis";
		side=0;
		faction="OPF_A_F";
		crew="O_A_soldier_F";
		typicalCargo[]=
		{
			"O_A_soldier_F"
		};
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_fuel_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa"
		};
	};
	class O_Truck_02_MRL_F: Truck_02_MRL_base_F
	{
		author="$STR_A3_Night515";
		mapSize=9.1800003;
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_Truck_02_MRL_F.jpg";
		_generalMacro="O_Truck_02_MRL_F";
		scope=2;
		scopeCurator=2;
		displayName="Zamak MRL";
		side=0;
		faction="OPF_F";
		crew="O_soldier_F";
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa",
			"\A3\Soft_F_Gamma\Truck_02\Data\Truck_02_MRL_OPFOR_CO.paa"
		};
	};
	class O_T_Truck_02_MRL_ghex_F: Truck_02_MRL_base_F
	{
		author="$STR_A3_Night515";
		mapSize=9.1800003;
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_T_Truck_02_MRL_ghex_F.jpg";
		_generalMacro="O_A_Truck_02_MRL_F";
		scope=2;
		scopeCurator=2;
		displayName="Zamak MRL";
		side=0;
		faction="OPF_T_F";
		crew="O_T_Soldier_F";
		textureList[]=
		{
			"GreenHex",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_kab_ghex_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa",
			"\A3\Soft_F_Aegis\Truck_02\Data\Truck_02_MRL_ghex_CO.paa"
		};
	};
	class O_A_Truck_02_MRL_F: Truck_02_MRL_base_F
	{
		author="$STR_A3_Night515";
		mapSize=9.1800003;
		editorPreview="\A3\EditorPreviews_F_Aegis\Data\CfgVehicles\O_A_Truck_02_MRL_F.jpg";
		_generalMacro="O_A_Truck_02_MRL_F";
		scope=2;
		scopeCurator=2;
		displayName="Zamak MRL";
		side=0;
		faction="OPF_A_F";
		crew="O_A_soldier_F";
		textureList[]=
		{
			"Opfor",
			1
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_kab_OPFOR_CO.paa",
			"\A3\Soft_F_Beta\Truck_02\Data\Truck_02_int_CO.paa",
			"\A3\Soft_F_Gamma\Truck_02\Data\Truck_02_MRL_OPFOR_CO.paa"
		};
	};
};
class cfgMods
{
	author="Night515";
	timepacked="1527942538";
};
