class CfgPatches
{
	class A3_Data_F_Aegis
	{
		author="$STR_A3_Night515";
		name="Arma 3 Aegis - Main Configuration";
		url="https://forums.bistudio.com/forums/topic/205858-arma-3-aegis-alpha";
		requiredAddons[]=
		{
			"A3_Data_F",
			"A3_Data_F_Exp",
			"A3_Data_F_Exp_Loadorder"
		};
		requiredVersion=0.1;
		units[]={};
		weapons[]={};
	};
};
class CfgAddons
{
	class PreloadAddons
	{
		class A3_Aegis
		{
			list[]=
			{
				"A3_Air_F_Aegis",
				"A3_Air_F_Aegis_Heli_Attack_01",
				"A3_Air_F_Aegis_Heli_Attack_02",
				"A3_Air_F_Aegis_Heli_Light_01",
				"A3_Air_F_Aegis_Heli_Light_02",
				"A3_Air_F_Aegis_Heli_Light_03",
				"A3_Air_F_Aegis_Heli_Transport_01",
				"A3_Air_F_Aegis_Heli_Transport_02",
				"A3_Air_F_Aegis_Heli_Transport_03",
				"A3_Air_F_Aegis_Heli_Transport_04",
				"A3_Air_F_Aegis_Plane_CAS_01",
				"A3_Air_F_Aegis_Plane_CAS_02",
				"A3_Air_F_Aegis_Plane_Fighter_01",
				"A3_Air_F_Aegis_Plane_Fighter_02",
				"A3_Air_F_Aegis_Plane_Fighter_03",
				"A3_Air_F_Aegis_Plane_Fighter_04",
				"A3_Air_F_Aegis_Plane_Fighter_05",
				"A3_Air_F_Aegis_Plane_Transport_01",
				"A3_Air_F_Aegis_UAV_01",
				"A3_Air_F_Aegis_UAV_02",
				"A3_Air_F_Aegis_UAV_03",
				"A3_Air_F_Aegis_UAV_04",
				"A3_Air_F_Aegis_UAV_05",
				"A3_Air_F_Aegis_UAV_06",
				"A3_Air_F_Aegis_VTOL_01",
				"A3_Air_F_Aegis_VTOL_02",
				"A3_Anims_F_Aegis",
				"A3_Armor_F_Aegis",
				"A3_Armor_F_Aegis_AFV_Wheeled_01",
				"A3_Armor_F_Aegis_APC_Tracked_01",
				"A3_Armor_F_Aegis_APC_Tracked_02",
				"A3_Armor_F_Aegis_APC_Tracked_03",
				"A3_Armor_F_Aegis_APC_Wheeled_01",
				"A3_Armor_F_Aegis_APC_Wheeled_02",
				"A3_Armor_F_Aegis_APC_Wheeled_03",
				"A3_Armor_F_Aegis_LT_01",
				"A3_Armor_F_Aegis_MBT_01",
				"A3_Armor_F_Aegis_MBT_02",
				"A3_Armor_F_Aegis_MBT_03",
				"A3_Armor_F_Aegis_MBT_04",
				"A3_BaseConfig_F_Aegis",
				"A3_Boat_F_Aegis",
				"A3_Boat_F_Aegis_Boat_Armed_01",
				"A3_Boat_F_Aegis_Boat_Civil_01",
				"A3_Boat_F_Aegis_Boat_Civil_02",
				"A3_Boat_F_Aegis_Boat_Transport_01",
				"A3_Boat_F_Aegis_Boat_Transport_02",
				"A3_Boat_F_Aegis_SDV_01",
				"A3_Cargoposes_F_Aegis",
				"A3_Characters_F_Aegis",
				"A3_Characters_F_Aegis_BLUFOR",
				"A3_Characters_F_Aegis_Civil",
				"A3_Characters_F_Aegis_Common",
				"A3_Characters_F_Aegis_Facewear",
				"A3_Characters_F_Aegis_Headgear",
				"A3_Characters_F_Aegis_Indep",
				"A3_Characters_F_Aegis_OPFOR",
				"A3_Characters_F_Aegis_Uniforms",
				"A3_Characters_F_Aegis_Vests",
				"A3_Data_F_Aegis",
				"A3_Data_F_Aegis_Loadorder",
				"A3_Data_F_Aegis_ParticleEffects",
				"A3_Data_F_Core",
				"A3_Dubbing_Radio_F_Aegis",
				"A3_EditorPreviews_F_Aegis",
				"A3_Functions_F_Aegis",
				"A3_Language_F_Aegis",
				"A3_Music_F_Aegis",
				"A3_Props_F_Aegis",
				"A3_Props_F_Aegis_Civilian",
				"A3_Props_F_Aegis_Civilian_Camps",
				"A3_Props_F_Aegis_Electronics",
				"A3_Props_F_Aegis_Items",
				"A3_Props_F_Aegis_Items_Electronics",
				"A3_Props_F_Aegis_Items_Military",
				"A3_Props_F_Aegis_Military",
				"A3_Props_F_Aegis_Military_Supplies",
				"A3_Soft_F_Aegis",
				"A3_Soft_F_Aegis_LSV_01",
				"A3_Soft_F_Aegis_LSV_02",
				"A3_Soft_F_Aegis_MRAP_01",
				"A3_Soft_F_Aegis_MRAP_02",
				"A3_Soft_F_Aegis_MRAP_03",
				"A3_Soft_F_Aegis_Offroad_01",
				"A3_Soft_F_Aegis_Quadbike_01",
				"A3_Soft_F_Aegis_SUV_01",
				"A3_Soft_F_Aegis_Tractor_01",
				"A3_Soft_F_Aegis_Truck_01",
				"A3_Soft_F_Aegis_Truck_02",
				"A3_Soft_F_Aegis_Truck_03",
				"A3_Soft_F_Aegis_UGV_01",
				"A3_Soft_F_Aegis_Van_01",
				"A3_Soft_F_Aegis_Van_02",
				"A3_Sounds_F_Aegis",
				"A3_Static_F_Aegis",
				"A3_Static_F_Aegis_AA_01",
				"A3_Static_F_Aegis_AAA_System_01",
				"A3_Static_F_Aegis_AT_01",
				"A3_Static_F_Aegis_Designator_01",
				"A3_Static_F_Aegis_Designator_02",
				"A3_Static_F_Aegis_GMG_01",
				"A3_Static_F_Aegis_HMG_01",
				"A3_Static_F_Aegis_Mortar_01",
				"A3_Static_F_Aegis_SAM_System_01",
				"A3_Static_F_Aegis_SAM_System_02",
				"A3_Structures_F_Aegis",
				"A3_Structures_F_Aegis_Humanitarian",
				"A3_Structures_F_Aegis_Humanitarian_Camps",
				"A3_Structures_F_Aegis_Military",
				"A3_Structures_F_Aegis_Military_Camonets",
				"A3_Structures_F_Aegis_Military_Flags",
				"A3_Structures_F_Aegis_Military_Fortifications",
				"A3_Structures_F_Aegis_Signs",
				"A3_Structures_F_Aegis_Signs_Warnings",
				"A3_Structures_F_Aegis_Wrecks",
				"A3_Supplies_F_Aegis",
				"A3_Supplies_F_Aegis_Ammoboxes",
				"A3_Supplies_F_Aegis_Bags",
				"A3_Supplies_F_Aegis_CargoNets",
				"A3_UI_F_Aegis",
				"A3_Weapons_F_Aegis",
				"A3_Weapons_F_Aegis_Acc",
				"A3_Weapons_F_Aegis_GrenadeLaunchers_M32",
				"A3_Weapons_F_Aegis_GrenadeLaunchers_XM25",
				"A3_Weapons_F_Aegis_Launchers_NLAW",
				"A3_Weapons_F_Aegis_Launchers_RPG32",
				"A3_Weapons_F_Aegis_Launchers_Titan",
				"A3_Weapons_F_Aegis_LongRangeRifles_DMR_01",
				"A3_Weapons_F_Aegis_LongRangeRifles_DMR_02",
				"A3_Weapons_F_Aegis_LongRangeRifles_DMR_03",
				"A3_Weapons_F_Aegis_LongRangeRifles_DMR_05",
				"A3_Weapons_F_Aegis_LongRangeRifles_DMR_06",
				"A3_Weapons_F_Aegis_LongRangeRifles_DMR_07",
				"A3_Weapons_F_Aegis_LongRangeRifles_EBR",
				"A3_Weapons_F_Aegis_LongRangeRifles_M320",
				"A3_Weapons_F_Aegis_LongRangeRifles_WF50",
				"A3_Weapons_F_Aegis_Machineguns_LMG_03",
				"A3_Weapons_F_Aegis_Machineguns_M200",
				"A3_Weapons_F_Aegis_Machineguns_MMG_01",
				"A3_Weapons_F_Aegis_Machineguns_MMG_02",
				"A3_Weapons_F_Aegis_Machineguns_Zafir",
				"A3_Weapons_F_Aegis_Pistols_ACPC2",
				"A3_Weapons_F_Aegis_Pistols_C1911",
				"A3_Weapons_F_Aegis_Pistols_G17",
				"A3_Weapons_F_Aegis_Pistols_Mk26",
				"A3_Weapons_F_Aegis_Pistols_P07",
				"A3_Weapons_F_Aegis_Pistols_Pistol_Heavy_01",
				"A3_Weapons_F_Aegis_Pistols_Rook40",
				"A3_Weapons_F_Aegis_Rifles_AK12",
				"A3_Weapons_F_Aegis_Rifles_CTAR",
				"A3_Weapons_F_Aegis_Rifles_CTARS",
				"A3_Weapons_F_Aegis_Rifles_Khaybar",
				"A3_Weapons_F_Aegis_Rifles_MK20",
				"A3_Weapons_F_Aegis_Rifles_MX",
				"A3_Weapons_F_Aegis_Rifles_MX_Black",
				"A3_Weapons_F_Aegis_Rifles_SA80",
				"A3_Weapons_F_Aegis_Rifles_SCAR",
				"A3_Weapons_F_Aegis_Rifles_SDAR",
				"A3_Weapons_F_Aegis_Rifles_SPAR_01",
				"A3_Weapons_F_Aegis_Rifles_SPAR_02",
				"A3_Weapons_F_Aegis_Rifles_SPAR_03",
				"A3_Weapons_F_Aegis_Rifles_TRG20",
				"A3_Weapons_F_Aegis_Shotguns_AA40",
				"A3_Weapons_F_Aegis_Shotguns_KSG",
				"A3_Weapons_F_Aegis_Shotguns_M4_SSAS",
				"A3_Weapons_F_Aegis_SMGs_Pdw2000",
				"A3_Weapons_F_Aegis_SMGs_SMG_01",
				"A3_Weapons_F_Aegis_SMGs_SMG_02",
				"A3_Weapons_F_Aegis_SMGs_SMG_05"
			};
		};
	};
};
class CfgFactionClasses
{
	class BLU_A_F
	{
		displayName="$STR_A3_CfgFactionClasses_BLU_A_F0";
		priority=6;
		side=1;
		icon="\A3\Data_F\CfgFactionClasses_BLU_CA.paa";
		flag="\A3\Data_F\Flags\Flag_NATO_CO.paa";
	};
	class BLU_ION_F
	{
		displayName="$STR_A3_CfgFactionClasses_BLU_ION_F0";
		priority=7;
		side=1;
		icon="\A3\Data_F_Aegis\FactionIcons\icon_ION_CA.paa";
		flag="\A3\Data_F_Aegis\Flags\Flag_ION_CO.paa";
	};
	class OPF_A_F
	{
		displayName="$STR_A3_CfgFactionClasses_OPF_A_F0";
		priority=5;
		side=0;
		icon="\A3\Data_F\CfgFactionClasses_OPF_CA.paa";
		flag="\A3\Data_F\Flags\Flag_CSAT_CO.paa";
	};
	class OPF_P_F
	{
		displayName="$STR_A3_CfgFactionClasses_OPF_P_F0";
		priority=6;
		side=0;
		icon="\A3\Data_F_Aegis\FactionIcons\icon_PARA_CA.paa";
		flag="\A3\Data_F_Aegis\Flags\Flag_Paramilitary_CO.paa";
	};
	class IND_R_F
	{
		displayName="$STR_A3_CfgFactionClasses_IND_R_F0";
		priority=5;
		side=2;
		icon="\A3\Data_F_Rus\FactionIcons\icon_RUS_CA.paa";
		flag="\A3\Data_F_Rus\Flags\Flag_Russia_CO.paa";
	};
};
class CfgVehicleClasses
{
};
class CfgMods
{
	class Mod_Base;
	class Aegis: Mod_Base
	{
		picture="\A3\Data_F_Aegis\Logos\arma3_Aegis_icon_CA.paa";
		logo="\A3\Data_F_Aegis\Logos\arma3_Aegis_logo_CA.paa";
		logoOver="\A3\Data_F_Aegis\Logos\arma3_Aegis_logoOver_CA.paa";
		logoSmall="\A3\Data_F_Aegis\Logos\arma3_Aegis_logo_small_CA.paa";
		tooltip="$STR_A3_cfgMods_Aegis_name0";
		tooltipOwned="$STR_A3_cfgMods_Aegis_name0";
		action="https://forums.bistudio.com/forums/topic/205858-arma-3-aegis-alpha";
		fieldManualTopicAndHint[]={};
		dlcColor[]={0.57999998,0.81999999,0.88999999,1};
		overview="$STR_A3_cfgMods_Aegis_overview0";
		logoTitle="\A3\Data_F_Aegis\Logos\arma3_Aegis_logoTitle_CA.paa";
		hideName=1;
		hidePicture=0;
		name="$STR_A3_cfgMods_Aegis_name0";
		author="$STR_A3_Night515";
		artwork="\A3\Data_F_Aegis\Logos\arma3_Aegis_artwork.jpg";
		overviewPicture="\A3\Data_F_Aegis\Images\Aegis_overviewPicture_CO.paa";
		dir="Aegis";
		class Assets
		{
		};
		class Features
		{
		};
	};
	author="Night515";
	timepacked="1527889989";
};
class CfgEditorCategories
{
};
class CfgEditorSubcategories
{
	class EdSubcat_GrenadeLaunchers
	{
		displayName="$STR_A3_CfgEditorSubcategories_EdSubcat_GrenadeLaunchers0";
	};
	class EdSubcat_Shotguns
	{
		displayName="$STR_A3_CfgEditorSubcategories_EdSubcat_Shotguns0";
	};
};
