class CfgPatches
{
	class A3_Characters_F_Aegis_Facewear
	{
		addonRootClass="A3_Characters_F_Aegis";
		requiredAddons[]=
		{
			"A3_Characters_F",
			"A3_Characters_F_Exp",
			"A3_Characters_F_Heads",
			"A3_Characters_F_Orange_Facewear"
		};
		requiredVersion=0.1;
		units[]={};
		weapons[]={};
	};
};
class CfgGlasses
{
	class None;
	class G_Spectacles: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20
		};
	};
	class G_Spectacles_Tinted: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20
		};
	};
	class G_Combat: None
	{
		model="\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_G_F.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"",
			"\A3\Characters_F\Heads\Glasses\Data\G_Combat_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			300,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			300,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class G_Lowprofile: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			150,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class G_Shades_Black: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
	};
	class G_Shades_Blue: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
	};
	class G_Shades_Green: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
	};
	class G_Shades_Red: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
	};
	class G_Shades_Yellowred: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Shades_Yellowred";
		displayname="$STR_A3_CfgGlasses_G_Shades_Yellowred0";
		model="\A3\Characters_F\Heads\Glasses\G_Shades_Black.p3d";
		picture="\A3\Characters_F\Data\UI\icon_G_Shades_Red_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Heads\Glasses\Data\joeyx_yellowred_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			20,
			"G_HAF_default",
			20,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			20,
			"G_Competitor",
			10
		};
		mass=2;
		DLC="Aegis";
	};
	class G_Squares: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			15
		};
	};
	class G_Squares_Tinted: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			10,
			"G_CIVIL_male",
			15
		};
	};
	class G_Sport_Blackred: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
	};
	class G_Sport_BlackWhite: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
	};
	class G_Sport_Blackyellow: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
	};
	class G_Sport_Greenblack: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
	};
	class G_Sport_Checkered: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
	};
	class G_Sport_Red: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			5,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			25
		};
	};
	class G_Tactical_Clear: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			10
		};
	};
	class G_Tactical_Black: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			10
		};
	};
	class G_Tactical_Yellow: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Tactical_Yellow";
		displayname="$STR_A3_CfgGlasses_G_Tactical_Yellow";
		model="\A3\Characters_F_Beta\Heads\Glasses\G_Tactical_Black";
		picture="\A3\Characters_F\Data\UI\icon_G_Tactical_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Heads\Glasses\Data\Tactical_2_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			10
		};
		mass=2;
		DLC="Aegis";
	};
	class G_Tactical_Camo: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Tactical_Camo";
		displayname="$STR_A3_CfgGlasses_G_Tactical_Camo0";
		model="\A3\Characters_F_Beta\Heads\Glasses\G_Tactical_Black";
		picture="\A3\Characters_F\Data\UI\icon_G_Tactical_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Heads\Glasses\Data\Tactical_4_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			10
		};
		mass=2;
		DLC="Aegis";
	};
	class G_Aviator: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			50,
			"G_NATO_casual",
			450,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			15,
			"G_NATO_SF",
			50,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			25,
			"G_HAF_default",
			25,
			"G_CIVIL_female",
			15,
			"G_CIVIL_male",
			30,
			"G_IRAN_officer",
			500
		};
	};
	class G_Lady_Mirror: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
	};
	class G_Lady_Dark: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
	};
	class G_Lady_Red: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
	};
	class G_Lady_Blue: None
	{
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			0,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			0,
			"G_NATO_SF",
			0,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			0,
			"G_CIVIL_female",
			40,
			"G_CIVIL_male",
			0
		};
	};
	class G_Diving;
	class G_O_Diving_ghex_F: G_Diving
	{
		author="$STR_A3_Night515";
		_generalMacro="G_O_Diving_ghex_F";
		displayname="$STR_A3_CfgGlasses_G_O_Diving_ghex_F0";
		model="\A3\Characters_F_EPB\Heads\Glasses\G_O_Diving.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_O_Diving_ghex_F_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\G_O_Diving_ghex_F_CA.paa"
		};
		identityTypes[]={};
		DLC="Aegis";
	};
	class G_Balaclava_blk;
	class G_Balaclava_Skull1: G_Balaclava_blk
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Balaclava_Skull1";
		displayname="$STR_A3_CfgGlasses_G_Balaclava_Skull10";
		model="\A3\Characters_F_Bootcamp\Guerrilla\G_balaclava_clean.p3d";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Balaclava_clean_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\headgear_balaclava_Skull1_CO.paa"
		};
		identityTypes[]={};
		DLC="Aegis";
	};
	class G_Bandanna_blk;
	class G_Bandanna_CandySkull: G_Bandanna_blk
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Bandanna_CandySkull";
		displayname="$STR_A3_CfgGlasses_G_Bandanna_CandySkull0";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_clean_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\headgear_bandmask_CandySkull_CO.paa"
		};
		identityTypes[]={};
		DLC="Aegis";
	};
	class G_Bandanna_Skull1: G_Bandanna_blk
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Bandanna_Skull1";
		displayname="$STR_A3_CfgGlasses_G_Bandanna_Skull10";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_clean_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\headgear_bandmask_Skull1_CO.paa"
		};
		identityTypes[]={};
		DLC="Aegis";
	};
	class G_Bandanna_Skull2: G_Bandanna_blk
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Bandanna_Skull2";
		displayname="$STR_A3_CfgGlasses_G_Bandanna_Skull20";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_clean_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\headgear_bandmask_Skull2_CO.paa"
		};
		identityTypes[]={};
		DLC="Aegis";
	};
	class G_Bandanna_Syndikat1: G_Bandanna_blk
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Bandanna_Syndikat1";
		displayname="$STR_A3_CfgGlasses_G_Bandanna_Syndikat10";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_clean_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\headgear_bandmask_Syndikat1_CO.paa"
		};
		identityTypes[]={};
		DLC="Aegis";
	};
	class G_Bandanna_Syndikat2: G_Bandanna_blk
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Bandanna_Syndikat2";
		displayname="$STR_A3_CfgGlasses_G_Bandanna_Syndikat20";
		picture="\A3\Characters_F_Bootcamp\Data\UI\icon_G_Bandana_clean_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\headgear_bandmask_Syndikat2_CO.paa"
		};
		identityTypes[]={};
		DLC="Aegis";
	};
	class G_Tactical_basic_F: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Tactical_basic_F";
		displayname="$STR_A3_CfgGlasses_G_Tactical_basic_F0";
		model="\A3\Characters_F_Aegis\Facewear\G_Tactical_F.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Tactical_basic_F_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\G_Tactical_F_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			0
		};
		mass=2;
		DLC="Aegis";
	};
	class G_Tactical_basic_black_F: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Shooting";
		displayname="$STR_A3_CfgGlasses_G_Tactical_basic_black_F0";
		model="\A3\Characters_F_Aegis\Facewear\G_Tactical_F.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Tactical_basic_F_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\G_Tactical_black_F_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			10,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			0
		};
		mass=2;
		DLC="Aegis";
	};
	class G_Shemag_grn: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Shemag_grn";
		displayname="$STR_A3_CfgGlasses_G_Shemag_grn0";
		model="\A3\Characters_F_Aegis\Facewear\G_Shemag.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Shemag_grn_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\BLUFOR\Data\armor1_CO.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			0
		};
		mass=8;
		DLC="Aegis";
	};
	class G_Shemag_gry: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Shemag_gry";
		displayname="$STR_A3_CfgGlasses_G_Shemag_gry0";
		model="\A3\Characters_F_Aegis\Facewear\G_Shemag.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Shemag_gry_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Beta\INDEP\Data\armor1_blk.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			0
		};
		mass=8;
		DLC="Aegis";
	};
	class G_Shemag_oli: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Shemag_oli";
		displayname="$STR_A3_CfgGlasses_G_Shemag_oli0";
		model="\A3\Characters_F_Aegis\Facewear\G_Shemag.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Shemag_oli_CA.paa";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Beta\INDEP\Data\armor1_oli_CO.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			100,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			10,
			"G_NATO_SF",
			100,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			10,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0,
			"G_Competitor",
			0
		};
		mass=8;
		DLC="Aegis";
	};
	class G_Headset_light: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Headset_light";
		displayname="$STR_A3_CfgWeapons_H_Headset_light0";
		model="\A3\Characters_F\Common\headset_light.p3d";
		picture="\A3\Characters_F_Aegis\Headgear\Data\UI\icon_H_Headset_light_CA.paa";
		identityTypes[]={};
		mass=2;
		DLC="Aegis";
	};
	class G_Cigarette_F: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Cigarette_F";
		displayname="$STR_A3_CfgGlasses_G_Cigarette_F0";
		model="\A3\Characters_F_Aegis\Facewear\G_Cigarette_F.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Cigarette_F_CA.paa";
		identityTypes[]={};
		mass=2;
		DLC="Aegis";
	};
	class G_Balaclava_TI_blk_F;
	class G_Balaclava_TI_G_blk_F: G_Balaclava_TI_blk_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Balaclava_TI_blk_F_CO.paa",
			"\A3\Characters_F\Heads\Glasses\data\g_combat_CA.paa"
		};
	};
	class G_Balaclava_TI_tna_F;
	class G_Balaclava_TI_G_tna_F: G_Balaclava_TI_tna_F
	{
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Balaclava_TI_tna_F_CO.paa",
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Combat_Goggles_tna_F_CA.paa"
		};
	};
	class G_Balaclava_TI_alt_F: G_Balaclava_TI_blk_F
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Balaclava_TI_alt_F";
		displayname="$STR_A3_CfgGlasses_G_Balaclava_TI_alt_F0";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Balaclava_TI_alt_F_CA.paa";
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\G_Balaclava_TI_alt_F_CO.paa"
		};
		identityTypes[]={};
		mass=6;
		DLC="Aegis";
	};
	class G_Balaclava_TI_G_alt_F: G_Balaclava_TI_alt_F
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Balaclava_TI_G_alt_F";
		displayname="$STR_A3_CfgGlasses_G_Balaclava_TI_G_alt_F0";
		model="\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_G_F.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Balaclava_TI_G_alt_F_CA.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F_Aegis\Facewear\Data\G_Balaclava_TI_alt_F_CO.paa",
			"\A3\Characters_F\Heads\Glasses\Data\G_Combat_CA.paa"
		};
		identityTypes[]={};
		mass=10;
		DLC="Aegis";
	};
	class G_Combat_Goggles_tna_F: None
	{
		model="\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_G_F.p3d";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"",
			"\A3\Characters_F_Exp\BLUFOR\Data\G_Combat_Goggles_tna_F_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			300,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			300,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
	};
	class G_Combat_Goggles_blk_F: None
	{
		author="$STR_A3_Night515";
		_generalMacro="G_Combat_Goggles_blk_F";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		displayname="$STR_A3_G_Combat_Goggles_blk_F0";
		model="\A3\Characters_F_Exp\BLUFOR\G_Balaclava_TI_G_F.p3d";
		picture="\A3\Characters_F_Aegis\Facewear\Data\UI\icon_G_Combat_Goggles_blk_F_CA.paa";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"",
			"\A3\Characters_F_Aegis\Facewear\Data\G_Combat_Goggles_blk_F_CA.paa"
		};
		identityTypes[]=
		{
			"NoGlasses",
			0,
			"G_NATO_default",
			300,
			"G_NATO_casual",
			0,
			"G_NATO_pilot",
			0,
			"G_NATO_recon",
			50,
			"G_NATO_SF",
			300,
			"G_NATO_sniper",
			0,
			"G_NATO_diver",
			0,
			"G_IRAN_default",
			0,
			"G_IRAN_diver",
			0,
			"G_GUERIL_default",
			0,
			"G_HAF_default",
			50,
			"G_CIVIL_female",
			0,
			"G_CIVIL_male",
			0
		};
		mass=6;
		DLC="Aegis";
	};
};
class cfgMods
{
	author="Night515";
	timepacked="1528894336";
};
